### ISSUE TITLE
DTLS disconnected

### ISSUE THREAD

**Issue by einsteinarbert** [uav-project-com/apprtc#18]
**Browsers and versions affected**
app android

**Description**
gọi 1 lúc bị lỗi: DTLS disconnected
Stacktrace có thể là:
```
ERROR    2022-05-21 12:55:10,349 webapp2.py:1528] 'HTTP_USER_AGENT'
Traceback (most recent call last):
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/root/app_engine/apprtc.py", line 547, in get
    params = get_room_parameters(self.request, None, None, None)
  File "/root/app_engine/apprtc.py", line 170, in get_room_parameters
    user_agent = request.headers['User-Agent']
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webob-1.1.1/webob/headers.py", line 135, in __getitem__
    return self.environ[_trans_name(hname)]
KeyError: 'HTTP_USER_AGENT'
ERROR    2022-05-21 12:55:10,350 wsgi.py:279] 
Traceback (most recent call last):
  File "/root/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/root/app_engine/apprtc.py", line 547, in get
    params = get_room_parameters(self.request, None, None, None)
  File "/root/app_engine/apprtc.py", line 170, in get_room_parameters
    user_agent = request.headers['User-Agent']
  File "/root/google-cloud-sdk/platform/google_appengine/lib/webob-1.1.1/webob/headers.py", line 135, in __getitem__
    return self.environ[_trans_name(hname)]
```
**Steps to reproduce**
gọi 2 điện thoại 1 lúc lâu

**Expected results**
Gọi không bị ngắt giữa trừng

**Actual results**
DTLS disconnected

**Comment by einsteinarbert** [comment]
Thử mạng ở nhà + 3G 5 phút không thấy hiện tượng lỗi
